
// Read
export const READ_EMPLOY_PENDING = 'READ_EMPLOY_PENDING'
export const READ_EMPLOY_FULFILLED ='READ_EMPLOY_FULFILLED'
export const READ_EMPLOY_REJECTED = 'READ_EMPLOY_REJECTED'

// create 
export const CREATE_EMPLOY_PENDING = 'CREATE_EMPLOY_PENDING'
export const CREATE_EMPLOY_FULFILLED ='CREATE_EMPLOY_FULFILLED'
export const CREATE_EMPLOY_REJECTED = 'CREATE_EMPLOY_REJECTED'

// update
export const UPDATE_EMPLOY_PENDING = 'UPDATE_EMPLOY_PENDING'
export const UPDATE_EMPLOY_FULFILLED ='UPDATE_EMPLOY_FULFILLED'
export const UPDATE_EMPLOY_REJECTED = 'UPDATE_EMPLOY_REJECTED'

// Delete
export const DELETE_EMPLOY_PENDING = 'DELETE_EMPLOY_PENDING'
export const DELETE_EMPLOY_FULFILLED ='DELETE_EMPLOY_FULFILLED'
export const DELETE_EMPLOY_REJECTED = 'DELETE_EMPLOY_REJECTED'


