
// EMPLOY Read
export const READ_EMPLOY_PENDING = 'READ_EMPLOY_PENDING'
export const READ_EMPLOY_FULFILLED ='READ_EMPLOY_FULFILLED'
export const READ_EMPLOY_REJECTED = 'READ_EMPLOY_REJECTED'

// EMPLOY create 
export const CREATE_EMPLOY_PENDING = 'CREATE_EMPLOY_PENDING'
export const CREATE_EMPLOY_FULFILLED ='CREATE_EMPLOY_FULFILLED'
export const CREATE_EMPLOY_REJECTED = 'CREATE_EMPLOY_REJECTED'

// EMPLOY update
export const UPDATE_EMPLOY_PENDING = 'UPDATE_EMPLOY_PENDING'
export const UPDATE_EMPLOY_FULFILLED ='UPDATE_EMPLOY_FULFILLED'
export const UPDATE_EMPLOY_REJECTED = 'UPDATE_EMPLOY_REJECTED'

// EMPLOY Delete
export const DELETE_EMPLOY_PENDING = 'DELETE_EMPLOY_PENDING'
export const DELETE_EMPLOY_FULFILLED ='DELETE_EMPLOY_FULFILLED'
export const DELETE_EMPLOY_REJECTED = 'DELETE_EMPLOY_REJECTED'





// Product read
export const READ_PRODUCT_PENDING = 'READ_PRODUCT_PENDING'
export const READ_PRODUCT_FULFILLED ='READ_PRODUCT_FULFILLED'
export const READ_PRODUCT_REJECTED = 'READ_PRODUCT_REJECTED'

// Product Create
export const CREATE_PRODUCT_PENDING = 'CREATE_PRODUCT_PENDING'
export const CREATE_PRODUCT_FULFILLED ='CREATE_PRODUCT_FULFILLED'
export const CREATE_PRODUCT_REJECTED = 'CREATE_PRODUCT_REJECTED'

// Product Update
export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING'
export const UPDATE_PRODUCT_FULFILLED ='UPDATE_PRODUCT_FULFILLED'
export const UPDATE_PRODUCT_REJECTED = 'UPDATE_PRODUCT_REJECTED'


